services:
  - type: web
    plan: free
    name: bill_ocr
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bill_ocr.wsgi:application -k uvicorn.workers.UvicornWorker"
